---
- name: Configure static IP address
  community.general.nmcli:
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    type: "{{ item.type }}"
    method4: "{{ item.method4 }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    method6: "{{ item.method6 }}"
    state: "{{ item.state }}"
    autoconnect: "{{ item.autoconnect }}"
  loop: "{{ lookup('vars', inventory_hostname).network | list }}"
  when: lookup('vars', inventory_hostname).network is defined
  notify:
    - restart NetworkManager.service