---
- name: "Send {{ item }}.rsc script"
  command: scp "{{ playbook_dir }}/../roles/mikrotik/files/{{ item }}.rsc" admin@{{ansible_host}}:/{{ item }}.rsc
  delegate_to: localhost

- name: "Apply {{ item }}.rsc"
  routeros_command:
    commands: /import {{ item }}.rsc
  register: mikrotik_output
  failed_when: '"Script file loaded and executed successfully" not in mikrotik_output.stdout'

- name: "Remove {{ item }}.rsc"
  routeros_command:
    commands: "/file remove {{ item }}.rsc"
