---
- name: Add Docker CE repository
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: create dir - /etc/docker
  ansible.builtin.file:
    path: /etc/docker
    state: directory

- name: Install docker-ce
  ansible.builtin.package:
    name:
      - docker-ce-24.0.2
      - docker-ce-cli-24.0.2
      - containerd.io-1.6.21
      - nfs-utils-2.5.4
    state: present

- name: upload file - /etc/docker/daemon.json
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0640
  notify:
    - restart docker.service
