---

- name: include docker_services
  hosts:
    - services_nprod
  handlers:
    - import_tasks: "{{ playbook_dir }}/../handlers/docker_reload.yml"
  become: true
  any_errors_fatal: true
  gather_facts: false
  
  tasks:
    - name: deploy docker services
      ansible.builtin.include_role:
        name: docker_services
      vars:
        shared_files:
          - dns.yml
